### ISSUE TITLE
RoadMap v.1

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#624]

**Comment by blackchestnut** [comment]
- [x] simple prototype
- [x] link to issues#show
- [x] forecast by throughput
- [x] tooltip with issue.data
- [x] display modes (one page and fixed width)

**Comment by blackchestnut** [comment]
@Sfolt, сегдня прототип задиплою он кривой и ограниченный по функционалу. Виден будет только нам двоим (у остальных в меню его не будет). Хочу немного погонять его на реальных данных и пожить с ним, чтобы не ошибиться как в прошлый раз с 2-мя графиками.

**Comment by blackchestnut** [comment]
@Sfolt, дополнительно хотел с тобой проконсультироваться, а это лучше делать на реальных данных.

**Comment by blackchestnut** [comment]
- [x] error on vimocean/roadmap

**Comment by blackchestnut** [comment]
Без фильтров непонятно и бесполезно.
