### ISSUE TITLE
Add filter by columns for roadmap 1.01

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#646]

**Comment by blackchestnut** [comment]
- [x] если все включены, то от `created_at` до `closed_at`
- [x] можно отключить отображение любой колонки (считать по lifetime)
- [x] поправить tooltip чтобы не выезжал за границу экрана, либо просто увеличить отступ справа на графике

новые ошибки
- [x] исчезли даты
