### ISSUE TITLE
Roadmap 1.02

### ISSUE THREAD

**Issue by blackchestnut** [agileseason/agileseason-v1#733]

**Comment by blackchestnut** [comment]
Фичи
- [ ] на hover показывать lifetimes соответствующим цветом

Улучшения
- [ ] правильно находить `min_from` для нормализации старта
- [ ] использовать сортировку из колонок для сортировки открытых на roadmap-е

Ошибки
- [ ] как-то плохо работает нормализация по строкам при фильтрации по колонкам (см. скрин 1)
- [ ] изменение шкалы сбрасывает фильтр по колонкам

Тех.долг
- [ ] использовать классы вместо хешей для элементов Roadmap (возможно придется переименовать сервис RoadmapIssue, т.к. хорошее название для модели)

**Comment by blackchestnut** [comment]
Скрин 1.
![uploads/2015-10-26/5435da81-5b39-450e-bb81-e74f76d967e6/Agile Season 2015-10-26 22-40-07.png](https://agile-season-production.s3.amazonaws.com/uploads%2F2015-10-26%2F5435da81-5b39-450e-bb81-e74f76d967e6%2FAgile%20Season%202015-10-26%2022-40-07.png)

**Comment by agileseason-support** [comment]
test
